hawkular:
  url: https://yzamir-centos7-1.eng.lab.tlv.redhat.com:443
  username: hawkular
  password: aM0tVkm81he_ovm
  tenant: _ops
rules:
  - regex: .*
    tags:
      type: node
      hostname: example.com
  - regex: .*memory
    tags:
      units: byte
  - regex: .*cpu
    tags:
      units: cpu
